{
    'name': 'Orden de Trabajo',
    'version': '1.0',
    'summary': 'Personalizacion del modulo CRM',
    'description': 'Personalizacion exclusiva para la empresa TVP con el fin de adaptar el trabajo de los formatos del ODT y control de gastos',
    'category': 'Personalizacion',
    'author': 'Xmarts',
    'website': 'www.xmarts.com',
    'depends': ['base',
                'hr_attendance',
                'contacts',
                'hr',
                'fleet',
                'sale',
                'crm',
                'helpdesk',
                'hr_expense',
                'stock',
                'project',
                'hr_holidays',
                'sale_management',
                'timesheet_grid',
                'account'],
                
    'data': ['views/view.xml'],
    'installable': True,
    'aplication': True,
    'auto_install': False,
}


